# Generated by Django 6.1 on 2026-08-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=2, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
