# Generated by Django 6.1 on 2026-08-31 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='number',
            new_name='quantity',
        ),
    ]
