# Generated by Django 6.1 on 2026-08-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('password', models.CharField(max_length=250, verbose_name='گذرواژه')),
                ('password_2', models.CharField(max_length=250, verbose_name='تکرار گذرواژه')),
            ],
        ),
    ]
