# Generated by Django 6.1 on 2026-09-01 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_checkoutmodel_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupModel',
        ),
    ]
