# Generated by Django 6.1 on 2026-08-19 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 8, 19, 13, 32, 56, 920606, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
