# Generated by Django 6.1 on 2026-08-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
