# Generated by Django 6.1 on 2026-09-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_discountmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
