# Generated by Django 6.1 on 2026-09-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_discountmodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountmodel',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
            preserve_default=False,
        ),
    ]
