# Generated by Django 6.1 on 2026-09-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_discountmodel_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountmodel',
            name='percentage',
            field=models.PositiveIntegerField(),
        ),
    ]
