# Generated by Django 6.1 on 2026-09-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_discountmodel_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
