# Generated by Django 6.1 on 2026-09-05 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_discountmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountmodel',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.discountmodel'),
        ),
    ]
